---

- name: Checking if ansible_distribution_major_version and ansible_distribution are not defined
  fail:
    msg: "Ansible distribution or ansible distribution version are not defined"
  when: ansible_distribution_major_version is not defined or ansible_distribution is not defined

- name: Checking if target server is not CentOS 7
  fail:
    msg: "This role can only be run on CentOS 7 servers"
  when: ansible_distribution != "CentOS" or (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7")

- name: Importing the Elasticsearch public GPG key into rpm
  rpm_key:
    state: absent
    key: "{{ elasticsearch_rpm_key }}"
  become: yes

- name: Creating a new yum repository file for logstash
  template:
    src: logstash.repo.j2
    dest: "/etc/yum.repos.d/{{ logstash_repo_name }}"
  become: yes

- name: Installing logstash pkg from repo
  yum: 
    name: "{{ logstash_pkg_name }}"
    state: present
  become: yes

#- name: Configure openssl
#  template:
#    src: openssl.cnf.j2
#    dest: "/etc/pki/tls/{{ openssl_fileconf_name }}"
#  become: yes

#- name: Create self-signed SSL cert
#  command: openssl req -subj '/CN={{ elk_fqdn }}/' -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout {{ logstash_forwarder_key }} -out {{ logstash_forwarder_cert }}
#  become: yes
  
- name: Configure logstash
  template:
    src: 02-beats-input.conf.j2
    dest: "/etc/logstash/conf.d/{{ logstash_fileconf_name }}"
  become: yes

- name: Create log path if not exist
  file: 
    path: "{{ logstash_log_path }}"
    owner: logstash 
    group: root
    state: directory
    mode: 0775
  become: yes

- name: Configure syslog filter
  template:
    src: 10-syslog-filter.conf.j2
    dest: "/etc/logstash/conf.d/{{ logstash_syslog_filter }}"
  become: yes
 
- name: Logrotate log file
  template:
    src: logrotate.logstash.j2
    dest: /etc/logrotate.d/logstash
  become: yes
 
- name: Configure elasticsearch-output
  template:
    src: 30-elasticsearch-output.conf.j2
    dest: "/etc/logstash/conf.d/{{ logstash_elasticsearch_output }}"
  become: yes
  
- name: Configure logstash-service
  template:
    src: logstash.service.j2
    dest: "/lib/systemd/system/{{ logstash_service }}"
  become: yes
  
- name: Reload systemctl
  command: systemctl daemon-reload
  become: yes

- name: Logrotate configuration file
  template:
    src: logrotate.logstash.j2
    dest: /etc/logrotate.d/logstash
  become: yes  
  
- name: Restart logstash
  service:
    name: "{{ logstash_service_name }}"
    state: restarted 
    enabled: yes
  become: yes
